apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: ahan-cluster-role-binding
  namespace: ahan-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ahan-cluster-admins
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: ahan-eks-cluster-group
